window.gameState = {
    currentTheme: 'futbol',
    difficulty: 'easy',
    mode: 'solitario',
    boardLocked: false,
    movesCount: 0,
    pairsFound: 0,
    totalPairsInBoard: 0,
    timeSeconds: 0,
    timerInterval: null,
    firstCardSelected: null,
    secondCardSelected: null,
    activeTurn: 1,
    p1Pairs: 0,
    p2Pairs: 0,
    currentStreak: 0,
    maxConsecutiveStreak: 0,
    currentFailStreak: 0,
    maxFailStreak: 0,
    isFirstAttempt: true,
    player1Name: 'Jugador 1',
    player2Name: 'Jugador 2',
    unlockedAchievements: new Set(),
    mistakesCount: 0,
    timedOut: false,
    resetCount: 0
};